server:
  port: 7000

eureka:
  instance:
    hostname: simple
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/